version: 1
groups:
    - annotation: content configuration
      options:
          - key: ckanext.content.schemas
            type: list
            default: ckanext.content:schemas/content/page.yaml ckanext.content:schemas/content/blog.yaml
          - key: ckanext.content.presets
            type: list
            default: ckanext.content:schemas/content/presets.yaml
          - key: ckanext.content.form_snippets_path
            type: list
            default: content/form_snippets/
          - key: ckanext.content.display_snippets_path
            type: list
            default: content/display_snippets/
