version: 1
groups:
    - annotation: content configuration
      options:
          - key: ckanext.content.schemas
            type: list
            default: ckanext.content:schemas/content/page.yaml ckanext.content:schemas/content/blog.yaml
          - key: ckanext.content.presets
            type: list
            default: ckanext.content:schemas/content/presets.yaml
          - key: ckanext.content.form_snippets_path
            type: list
            default: content/form_snippets/
          - key: ckanext.content.display_snippets_path
            type: list
            default: content/display_snippets/
          - key: ckan.upload.content.mimetypes
            type: list
            default: image/png image/gif image/jpeg text/csv application/pdf application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document application/zip application/json text/plain